apiVersion: v1
kind: Service
metadata:
  name: caculator-svc
  namespace: cloudnative
spec:
  selector:
    app: caculator-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
