apiVersion: v1
kind: Service
metadata:
  name: http-server-demo
  namespace: cloudnative
spec:
  selector:
    app: http-server-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
